image: 
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - name : update
    init: composer update && gp sync-done update
    command: echo "Composer update"

  - name : server start
    init : gp sync-await update
    command : symfony server:start
    
vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client