image: 
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - name : server start
    init : composer update
    command : symfony server:start

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client